import { categories, tools } from './seed-data.mjs'

const esc = (v) => v == null ? 'NULL' : `'${String(v).replace(/'/g, "''")}'`
const bool = (v) => v ? 'TRUE' : 'FALSE'

const lines = []
lines.push('-- ============================================================================')
lines.push('-- AI 工具集导航 —— 表结构 + 种子数据 + 写入 RPC')
lines.push('-- 来源：app/page.tsx 的 categories / tools 数组 (24 个工具 + 12 个分类)')
lines.push('-- 使用方式：')
lines.push('--   1. Supabase Dashboard -> SQL Editor -> 粘贴执行 (一次性)')
lines.push('--   2. 项目自带 scripts/seed-supabase.mjs (后续修改 seed-data 后幂等 upsert)')
lines.push('-- 注意：表名加 ai_ 前缀，避免与现有 categories / records 等表冲突。')
lines.push('-- RLS 仅在 Supabase 环境生效（依赖 anon/authenticated 角色）。')
lines.push('-- 本脚本全部幂等：可以反复执行。')
lines.push('-- ============================================================================')
lines.push('')

lines.push('-- 1. 分类表 ----------------------------------------------------------')
lines.push(`CREATE TABLE IF NOT EXISTS public.ai_categories (`)
lines.push(`  id          BIGSERIAL PRIMARY KEY,`)
lines.push(`  slug        TEXT NOT NULL UNIQUE,`)
lines.push(`  name        TEXT NOT NULL,`)
lines.push(`  icon        TEXT,`)
lines.push(`  sort_order  INTEGER NOT NULL DEFAULT 0,`)
lines.push(`  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()`)
lines.push(`);`)
lines.push('')

lines.push('-- 2. 工具表 ----------------------------------------------------------')
lines.push(`CREATE TABLE IF NOT EXISTS public.ai_tools (`)
lines.push(`  id           BIGSERIAL PRIMARY KEY,`)
lines.push(`  slug         TEXT NOT NULL UNIQUE,`)
lines.push(`  name         TEXT NOT NULL,`)
lines.push(`  description  TEXT,`)
lines.push(`  category_id  BIGINT NOT NULL REFERENCES public.ai_categories(id) ON DELETE RESTRICT,`)
lines.push(`  color        TEXT,`)
lines.push(`  letter       TEXT,`)
lines.push(`  url          TEXT,`)
lines.push(`  logo_url     TEXT,`)
lines.push(`  preview_url  TEXT,`)
lines.push(`  is_featured  BOOLEAN NOT NULL DEFAULT FALSE,`)
lines.push(`  is_latest    BOOLEAN NOT NULL DEFAULT FALSE,`)
lines.push(`  sort_order   INTEGER NOT NULL DEFAULT 0,`)
lines.push(`  created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),`)
lines.push(`  updated_at   TIMESTAMPTZ NOT NULL DEFAULT NOW()`)
lines.push(`);`)
lines.push('')

lines.push(`CREATE INDEX IF NOT EXISTS idx_ai_tools_category  ON public.ai_tools(category_id);`)
lines.push(`CREATE INDEX IF NOT EXISTS idx_ai_tools_featured  ON public.ai_tools(is_featured);`)
lines.push(`CREATE INDEX IF NOT EXISTS idx_ai_tools_latest    ON public.ai_tools(is_latest);`)
lines.push(`CREATE INDEX IF NOT EXISTS idx_ai_tools_slug      ON public.ai_tools(slug);`)
lines.push('')

lines.push('-- 3. RLS —— 仅在 Supabase 环境生效 (依赖 anon / authenticated 角色) ----')
lines.push(`DO $$`)
lines.push(`BEGIN`)
lines.push(`  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname='anon') THEN`)
lines.push(`    ALTER TABLE public.ai_categories ENABLE ROW LEVEL SECURITY;`)
lines.push(`    ALTER TABLE public.ai_tools     ENABLE ROW LEVEL SECURITY;`)
lines.push(`    EXECUTE 'DROP POLICY IF EXISTS "anon read ai_categories" ON public.ai_categories';`)
lines.push(`    EXECUTE 'CREATE POLICY "anon read ai_categories" ON public.ai_categories FOR SELECT TO anon, authenticated USING (true)';`)
lines.push(`    EXECUTE 'DROP POLICY IF EXISTS "anon read ai_tools" ON public.ai_tools';`)
lines.push(`    EXECUTE 'CREATE POLICY "anon read ai_tools" ON public.ai_tools FOR SELECT TO anon, authenticated USING (true)';`)
lines.push(`  END IF;`)
lines.push(`END`)
lines.push(`$$;`)
lines.push('')

lines.push('-- 4. 写入 RPC (供 Node 脚本调用，做真正幂等的 upsert) ----------------')
lines.push('-- 用 ON CONFLICT (slug) DO UPDATE 解决 PostgREST merge-duplicates 不可用的问题')
lines.push(`CREATE OR REPLACE FUNCTION public.ai_upsert_categories(p_rows jsonb)`)
lines.push(`RETURNS integer`)
lines.push(`LANGUAGE plpgsql`)
lines.push(`SECURITY DEFINER`)
lines.push(`AS $$`)
lines.push(`DECLARE`)
lines.push(`  affected integer;`)
lines.push(`BEGIN`)
lines.push(`  INSERT INTO public.ai_categories (slug, name, icon, sort_order)`)
lines.push(`  SELECT r.slug, r.name, r.icon, r.sort_order`)
lines.push(`  FROM jsonb_to_recordset(p_rows) AS r(slug text, name text, icon text, sort_order int)`)
lines.push(`  ON CONFLICT (slug) DO UPDATE SET`)
lines.push(`    name       = EXCLUDED.name,`)
lines.push(`    icon       = EXCLUDED.icon,`)
lines.push(`    sort_order = EXCLUDED.sort_order;`)
lines.push(`  GET DIAGNOSTICS affected = ROW_COUNT;`)
lines.push(`  RETURN affected;`)
lines.push(`END;`)
lines.push(`$$;`)
lines.push('')

lines.push(`CREATE OR REPLACE FUNCTION public.ai_upsert_tools(p_rows jsonb)`)
lines.push(`RETURNS integer`)
lines.push(`LANGUAGE plpgsql`)
lines.push(`SECURITY DEFINER`)
lines.push(`AS $$`)
lines.push(`DECLARE`)
lines.push(`  affected integer;`)
lines.push(`BEGIN`)
lines.push(`  -- 先把分类 upsert 一遍（如果前端先调 categories 不会出问题，但保险起见内部也处理）`)
lines.push(`  INSERT INTO public.ai_categories (slug, name, icon, sort_order)`)
lines.push(`  SELECT DISTINCT r.category_slug, r.category_name, r.category_icon, 0`)
lines.push(`  FROM jsonb_to_recordset(p_rows) AS r(category_slug text, category_name text, category_icon text)`)
lines.push(`  ON CONFLICT (slug) DO NOTHING;`)
lines.push(``)
lines.push(`  INSERT INTO public.ai_tools (slug, name, description, category_id, color, letter, url, is_featured, is_latest, sort_order, updated_at)`)
lines.push(`  SELECT`)
lines.push(`    r.slug, r.name, r.description, c.id, r.color, r.letter, r.url,`)
lines.push(`    COALESCE(r.is_featured, false), COALESCE(r.is_latest, false), COALESCE(r.sort_order, 0), NOW()`)
lines.push(`  FROM jsonb_to_recordset(p_rows) AS r(`)
lines.push(`    slug text, name text, description text,`)
lines.push(`    category_slug text, category_name text, category_icon text,`)
lines.push(`    color text, letter text, url text,`)
lines.push(`    is_featured boolean, is_latest boolean, sort_order int`)
lines.push(`  )`)
lines.push(`  JOIN public.ai_categories c ON c.slug = r.category_slug`)
lines.push(`  ON CONFLICT (slug) DO UPDATE SET`)
lines.push(`    name        = EXCLUDED.name,`)
lines.push(`    description = EXCLUDED.description,`)
lines.push(`    category_id = EXCLUDED.category_id,`)
lines.push(`    color       = EXCLUDED.color,`)
lines.push(`    letter      = EXCLUDED.letter,`)
lines.push(`    url         = EXCLUDED.url,`)
lines.push(`    is_featured = EXCLUDED.is_featured,`)
lines.push(`    is_latest   = EXCLUDED.is_latest,`)
lines.push(`    sort_order  = EXCLUDED.sort_order,`)
lines.push(`    updated_at  = NOW();`)
lines.push(`  GET DIAGNOSTICS affected = ROW_COUNT;`)
lines.push(`  RETURN affected;`)
lines.push(`END;`)
lines.push(`$$;`)
lines.push('')

lines.push('-- 5. SELECT RPC (verify 用) -------------------------------------------')
lines.push(`CREATE OR REPLACE FUNCTION public.ai_list_tools_with_category()`)
lines.push(`RETURNS TABLE (`)
lines.push(`  slug text, name text, category_slug text, is_featured boolean, is_latest boolean, sort_order int`)
lines.push(`)`)
lines.push(`LANGUAGE sql`)
lines.push(`STABLE`)
lines.push(`SECURITY DEFINER`)
lines.push(`AS $$`)
lines.push(`  SELECT t.slug, t.name, c.slug AS category_slug, t.is_featured, t.is_latest, t.sort_order`)
lines.push(`  FROM public.ai_tools t`)
lines.push(`  JOIN public.ai_categories c ON c.id = t.category_id`)
lines.push(`  ORDER BY t.sort_order;`)
lines.push(`$$;`)
lines.push('')

lines.push('-- 6. 种子数据：分类 (幂等) --------------------------------------------')
lines.push(`INSERT INTO public.ai_categories (slug, name, icon, sort_order) VALUES`)
const catValues = categories.map((c, i) => {
  const comma = i === categories.length - 1 ? '' : ','
  return `  (${esc(c.slug)}, ${esc(c.name)}, ${esc(c.icon)}, ${c.sort_order})${comma}`
})
lines.push(...catValues)
lines.push(`ON CONFLICT (slug) DO UPDATE SET`)
lines.push(`  name = EXCLUDED.name,`)
lines.push(`  icon = EXCLUDED.icon,`)
lines.push(`  sort_order = EXCLUDED.sort_order;`)
lines.push('')

lines.push('-- 7. 种子数据：工具 (幂等) --------------------------------------------')
lines.push(`INSERT INTO public.ai_tools (slug, name, description, category_id, color, letter, url, is_featured, is_latest, sort_order)`)
lines.push(`SELECT v.slug, v.name, v.description, c.id, v.color, v.letter, v.url, v.is_featured, v.is_latest, v.sort_order`)
lines.push(`FROM (VALUES`)
const toolValues = tools.map((t, i) => {
  const comma = i === tools.length - 1 ? '' : ','
  const cat = categories.find((c) => c.name === t.category)
  if (!cat) throw new Error(`工具 ${t.slug} 找不到分类 ${t.category}`)
  return `    (${esc(t.slug)}::TEXT, ${esc(t.name)}::TEXT, ${esc(t.description)}::TEXT, ${esc(cat.slug)}::TEXT, ${esc(t.color)}::TEXT, ${esc(t.letter)}::TEXT, ${esc(t.url)}::TEXT, ${bool(t.is_featured)}::BOOLEAN, ${bool(t.is_latest)}::BOOLEAN, ${t.sort_order}::INTEGER)${comma}`
})
lines.push(...toolValues)
lines.push(`) AS v(slug, name, description, category_slug, color, letter, url, is_featured, is_latest, sort_order)`)
lines.push(`JOIN public.ai_categories c ON c.slug = v.category_slug`)
lines.push(`ON CONFLICT (slug) DO UPDATE SET`)
lines.push(`  name = EXCLUDED.name,`)
lines.push(`  description = EXCLUDED.description,`)
lines.push(`  category_id = EXCLUDED.category_id,`)
lines.push(`  color = EXCLUDED.color,`)
lines.push(`  letter = EXCLUDED.letter,`)
lines.push(`  url = EXCLUDED.url,`)
lines.push(`  is_featured = EXCLUDED.is_featured,`)
lines.push(`  is_latest = EXCLUDED.is_latest,`)
lines.push(`  sort_order = EXCLUDED.sort_order,`)
lines.push(`  updated_at = NOW();`)
lines.push('')

import fs from 'node:fs'
const out = lines.join('\n')
fs.writeFileSync('supabase/migrations/20250913_ai_tools_nav.sql', out, 'utf8')
fs.writeFileSync('supabase/seed/ai_tools_nav.sql', out, 'utf8')
console.log('rewrote SQL, bytes:', out.length)
